import { Manrope } from "next/font/google";
import "../styles/globals.scss";

const manrope = Manrope({ weight: ["200", "300", "400", "500", "600", "700", "800"], style: ["normal"], subsets: ["latin"], display: "swap", variable: "--font-manrope" });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={manrope.className}>{children}</body>
		</html>
	);
}
